# Generated by Django 3.2.7 on 2021-09-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_field',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
