# Generated by Django 3.2.7 on 2021-10-14 18:27

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20211007_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.get_file_path, verbose_name='Аватарка'),
        ),
    ]
