# Generated by Django 3.2.7 on 2021-09-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210915_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='0', max_length=32, verbose_name='Наименование на английском'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='0', max_length=32, verbose_name='Наименование на английском'),
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Наименование')),
                ('description', models.TextField(max_length=256, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Цена')),
                ('slug', models.SlugField(default='0', max_length=32, verbose_name='Наименование на английском')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
            ],
        ),
    ]
