# Generated by Django 3.2.7 on 2021-11-15 16:54

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_brandimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands', validators=[catalog.validators.validate_brand], verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='BrandImage',
        ),
    ]
