# Generated by Django 3.2.7 on 2021-09-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210924_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Brand',
        ),
    ]
