# Generated by Django 3.2.7 on 2021-11-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_brandimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='image',
        ),
    ]
