# Generated by Django 3.2.7 on 2021-11-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20211124_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Основная категория', 'verbose_name_plural': 'Основные категории'},
        ),
    ]
