# Generated by Django 3.2.7 on 2021-11-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_maincategory_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='main_category',
        ),
    ]
