# Generated by Django 3.2.7 on 2021-12-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20211125_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='addon',
        ),
        migrations.DeleteModel(
            name='Addon',
        ),
    ]
